# Generated by Django 2.1.5 on 2019-02-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='task',
        ),
        migrations.AddField(
            model_name='exam',
            name='task',
            field=models.ManyToManyField(related_name='exam_tasks', to='api_exams.Task'),
        ),
    ]
