# Generated by Django 2.1.5 on 2019-02-06 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_exams', '0002_exam_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
