# Generated by Django 2.1.5 on 2019-02-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_exams', '0002_auto_20190205_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='task',
            field=models.ManyToManyField(to='api_exams.Task'),
        ),
    ]
