# Generated by Django 2.1.5 on 2019-02-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_exams', '0003_auto_20190205_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
