# Generated by Django 2.1.5 on 2019-02-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_exams', '0003_auto_20190206_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='highlighted',
        ),
        migrations.AlterField(
            model_name='exam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
